---
title: "자바 : 예외(Exception)"
excerpt: 자바의 예외 객체에 대해 알아봅니다.
---

자바에서 예외란 실행 과정에서 잘못된 점이 있을 때 발생합니다.

예외의 종류에 따라 처리해야 될 것과 아닌 것으로 보통 세 가지로 분류됩니다.

- `Error`
- `RuntimeException`
- 그 외

Error 예외는 뭐가 잘못된 것인지 모를 정도로 심각해 발생된 예외입니다.

RuntimeException 예외는 보통 프로그래밍 버그이므로 고쳐야 하는 예외입니다.

그 외 예외는 상황에 따라 처리해주면 됩니다.

## 예외 종류

모든 예외는 `Throwable` 클래스로부터 상속되어서 `Error`, `Exception` 이 두 개의 클래스로 나눠집니다. `Exception`은 `RuntimeException`과 그 외로 다시 나눠집니다.

## 예외 생성

얘외 객체는 throw 키워드로 생성합니다.

### `throw` 키워드

어떤 메서드도 `throw` 키워드를 사용해 예외를 생성할 수 있습니다. `throw`는 `Throwable` 객체를 인수로 가집니다.

**참고**: `Throwable` 객체는 `Throwable` 클래스를 상속받는 자식 클래스들의 인스턴스입니다.
{: .notice--info}

`throw` 키워드를 다음과 같이 사용합니다.

```java
throw MyException;
```

### 연속적인 예외

어떤 프로그램은 예외를 처리하면 다른 예외를 발생시키기도 합니다. 이럴 때는 catch 문에서 맞는 예외 처리를 만날 때까지 메서드 체인을 거슬러 올라갑니다.

예를 들어 IOException이 발생한 경우 새로운 예외 객체를 생성하고 발생한 예외를 첨부합니다.

```java
try {
    ...
} catch (IOException e) {
    throw new MyException("다른 예외", e);
}
```

### 사용자가 정의한 예외

이미 존재하는 예외를 구분하여 처리할 필요가 있을 경우 사용자가 정의한 예외 클래스를 생성하면 됩니다.

```java
public class MyException extends Exception {
    ...
}
```

위 코드와 같이 `Exception`을 상속받으면 됩니다.

백문이 불여일견이라고 실제로 사용자 정의 예외를 발생시키는 코드를 작성해 봅니다.

**Input**:  
  
```java
class MyException extends Exception {
    
    public MyException() {
        super("사용자 정의 예외");
    }

}

public class MyExceptionTest {

    public static void main(String[] args) {
        try {
            throw new MyException();
        } catch (MyException e) {
            System.out.println(e.getMessage());
            System.out.print("호출 스택 내용: ");
            e.printStackTrace();
        }
    }
    
}
```

**Output**:

```shell
사용자 정의 예외
호출 스택 내용: Exception.MyException: 사용자 정의 예외
        at Exception.MyExceptionTest.main(MyExceptionTest.java:15)
```
